### ISSUE TITLE
Failed to make:foundation

### ISSUE THREAD

**Issue by ergonomicus** [evercode1/view-maker#1]
When I try 'php artisan make:foundation Widget master vue' I get this:

[ErrorException]
  fopen(/var/www/html/evercode/App/Widget.php): failed to open stream: No such file or directory

Note the 'App' instead of 'app' folder name...

**Comment by evercode1** [comment]
Fixed, thanks for catching that.

**Comment by ergonomicus** [comment]
Everything is fine now. Thanks!
