### ISSUE TITLE
create View based on database 

### ISSUE THREAD

**Issue by phpwebdev** [evercode1/view-maker#4]
Is there way to create views based on databas table 

For example  ... this is from migration file ....

    public function up()
    {
        Schema::create('trackings', function (Blueprint $table) {

            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->string('session_id');
            $table->string('buletin');
            $table->string('identification');
            $table->string('identificationTable');
            $table->timestamps();

            $table->index('session_id');
            $table->index('buletin');
            $table->index('identification');
            $table->index('identificationTable');
            $table->unique(['session_id','buletin','identification','identificationTable']);
        });
    }

May be i missed something ...  ???

This is my actions :
 
1) create foundation;
2) populate migration  files.
3) filled ModelFactory 
4) use php artisan command for  migrations
5) use make:view  command ..

but View files don't correspond  with my table structure .... 
on index.blade.php missing table sections .
on another files have only "tracker_name" field....

i try 
5.*) php artisan make:crud bud result are same 

Any idea  ?

**Comment by evercode1** [comment]
ViewMaker is working as intended.  ViewMaker will only create a single column, $model  . ' _name'.  It does not read your database to figure out what to put in the views.  If you want to add columns, use the make foundation command, then modify the migration before running it to add your custom columns.  You will also have to modify the model, controller, views, etc.

I have a screencast that shows the workflow for make:foundation:

https://www.youtube.com/watch?v=Q8KOqXHyulM

It talks briefly about adding columns.  Hope that helps.

**Comment by phpwebdev** [comment]
Thanks, All clear now
