### ISSUE TITLE
There is no routes.php anymore - append to routes/web.php routes/api.php?

### ISSUE THREAD

**Issue by tblanchard** [evercode1/view-maker#6]
Seems there are now 3 routes files under the folder routes.  So no routes are created on make:foundation.

**Comment by evercode1** [comment]
ViewMaker is not compatible with Laravel 5.3, only 5.2.  For Laravel 5.3 please use FoundationMaker:

https://github.com/evercode1/foundation-maker

Please read through the documentation carefully, this is a more robust implementation of the code generator and there are significant changes, thanks.
